platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Add the Firebase iOS SDK repository
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/firebase/Specs.git'

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with Xcode.
install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# cd ios - pod install 